items:
- name: Visual Studio Tools for Docker
  href: /dotnet/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker?toc=/visualstudio/docker/toc.json&bc=/visualstudio/docker/breadcrumb/toc.json
  items:
  - name: 'Szybki start: Visual Studio Tools for Docker'
    href: docker-tools.md
  - name: Debugowanie aplikacji w lokalnym kontenerze platformy Docker
    href: ../docker/vs-azure-tools-docker-edit-and-refresh.md
  - name: Wdrażanie kontenera platformy ASP.NET w rejestrze kontenerów przy użyciu programu Visual Studio
    href: ../docker/vs-azure-tools-docker-hosting-web-apps-in-docker.md
  - name: Konfigurowanie hosta platformy Docker przy użyciu rozwiązania VirtualBox
    href: ../docker/vs-azure-tools-docker-setup.md
  - name: Rozwiązywanie problemów związanych z opracowywaniem zwartości w programie Visual Studio 2017 przy użyciu platformy Docker
    href: ../docker/vs-azure-tools-docker-troubleshooting-docker-errors.md
  expanded: true
ms.openlocfilehash: 0d476d43454bdbba18ce3dba8baffab1108e4250
ms.sourcegitcommit: c0202a77d4dc562cdc55dc2e6223c062281d9749
ms.translationtype: HT
ms.contentlocale: pl-PL
ms.lasthandoff: 01/24/2019
ms.locfileid: "54874721"
